// Guías escritas y revisadas a mano por NoMore Errors.
// Cuando el código buscado coincide con una de estas guías, la web la muestra
// directamente sin consultar a la IA.

const GUIDE_CATEGORIES = {
  actualizaciones: { label: "Actualizaciones", icon: "⟳" },
  pantallazo: { label: "Pantallazo azul", icon: "◼" },
  programas: { label: "Programas", icon: "▣" },
  red: { label: "Internet", icon: "⌁" },
  sistema: { label: "Sistema", icon: "⚙" },
};

const GUIDE_LEVELS = {
  facil: "Fácil",
  media: "Intermedia",
  avanzada: "Avanzada",
};

const GUIDES = [
  {
    id: "wu-0x80070002",
    code: "0x80070002",
    aliases: [],
    category: "actualizaciones",
    level: "facil",
    time: "15–30 min",
    title: "Windows Update no termina de instalar",
    summary: "Los archivos de la actualización se descargaron mal o están incompletos.",
    explanation:
      "Windows descargó una actualización, pero al instalarla no encuentra algunos de sus archivos. Suele pasar si se cortó la descarga o se apagó el equipo a mitad. La solución es borrar la descarga para que Windows la baje de nuevo.",
    causes: [
      "La descarga de la actualización se interrumpió.",
      "El equipo se apagó o reinició mientras se instalaba.",
      "Algunos archivos del sistema están dañados.",
    ],
    steps: [
      {
        tipo: "configuracion",
        title: "Usa el solucionador de Windows Update",
        detail: "Windows trae una herramienta que revisa y repara los problemas más habituales de las actualizaciones.",
        how_to: "Configuración → Sistema → Solucionar problemas → Otros solucionadores de problemas → Windows Update → Ejecutar.",
      },
      {
        tipo: "terminal",
        title: "Borra la descarga dañada",
        detail: "Paramos el servicio de actualizaciones, apartamos la carpeta de descargas y lo volvemos a arrancar. No se borra nada tuyo.",
        how_to: "Abre la Terminal como administrador y pega estas líneas. Si dice que la carpeta .old ya existe, bórrala primero o cambia el nombre.",
        comando:
          "net stop wuauserv\nnet stop bits\nRename-Item C:\\Windows\\SoftwareDistribution SoftwareDistribution.old\nnet start bits\nnet start wuauserv",
        command_explanation: "Windows creará una carpeta SoftwareDistribution nueva y limpia al buscar actualizaciones.",
      },
      {
        tipo: "terminal",
        title: "Repara los archivos de Windows",
        detail: "Estos dos comandos comprueban que los archivos del sistema estén completos y reparan los dañados. Pueden tardar 10–20 minutos.",
        how_to: "En la misma Terminal de administrador, ejecuta primero DISM y, cuando termine, sfc.",
        comando: "DISM /Online /Cleanup-Image /RestoreHealth\nsfc /scannow",
        command_explanation: "DISM descarga piezas sanas de Windows; sfc las usa para reparar los archivos protegidos.",
      },
      {
        tipo: "reinicio",
        title: "Reinicia y vuelve a buscar actualizaciones",
        detail: "Reinicia el equipo y entra en Configuración → Windows Update → Buscar actualizaciones.",
        how_to: "Deja el equipo conectado al cargador y a Internet mientras descarga.",
      },
    ],
    help: "Si sigue fallando con la misma actualización, apunta su número (empieza por KB) y búscalo en el Catálogo de Microsoft Update para instalarla a mano.",
  },
  {
    id: "wu-0x8024402f",
    code: "0x8024402F",
    aliases: [],
    category: "actualizaciones",
    level: "facil",
    time: "5–15 min",
    title: "Windows Update no puede conectarse",
    summary: "El equipo no logra comunicarse con los servidores de Microsoft.",
    explanation:
      "Windows intenta buscar actualizaciones pero no consigue conectarse con Microsoft. Normalmente el problema está en la conexión: una VPN, un proxy, un antivirus o la fecha y hora del equipo mal puestas.",
    causes: [
      "Hay una VPN o un proxy activo que bloquea la conexión.",
      "La fecha y la hora del equipo no son correctas.",
      "Un antivirus o cortafuegos de terceros bloquea Windows Update.",
    ],
    steps: [
      {
        tipo: "configuracion",
        title: "Comprueba la fecha y la hora",
        detail: "Si la hora está mal, las conexiones seguras fallan.",
        how_to: "Configuración → Hora e idioma → Fecha y hora → activa «Establecer la hora automáticamente» y pulsa «Sincronizar ahora».",
      },
      {
        tipo: "configuracion",
        title: "Desactiva la VPN un momento",
        detail: "Desconecta la VPN o el proxy mientras actualizas. Cuando termine, vuelve a activarla.",
        how_to: "Configuración → Red e Internet → VPN y Proxy. En Proxy, deja activado solo «Detectar la configuración automáticamente».",
      },
      {
        tipo: "terminal",
        title: "Restablece el proxy del sistema",
        detail: "Borra cualquier proxy antiguo que haya quedado guardado y pueda estar bloqueando Windows Update.",
        how_to: "Abre la Terminal como administrador y ejecuta el comando.",
        comando: "netsh winhttp reset proxy",
        command_explanation: "Deja la conexión de Windows en modo directo, sin proxy.",
      },
      {
        tipo: "reinicio",
        title: "Reinicia el router y el equipo",
        detail: "Apaga el router 30 segundos, enciéndelo, reinicia el ordenador y vuelve a buscar actualizaciones.",
      },
    ],
    help: "Si es un ordenador del trabajo o del centro de estudios, puede que las actualizaciones las gestione su departamento de informática: avísales.",
  },
  {
    id: "wu-0x80070643",
    code: "0x80070643",
    aliases: [],
    category: "actualizaciones",
    level: "media",
    time: "10–20 min",
    title: "Error al instalar una actualización",
    summary: "Una actualización concreta no se puede instalar, aunque se descargó bien.",
    explanation:
      "Es un error genérico de instalación. Aparece mucho con actualizaciones de Microsoft Defender, de .NET Framework o de la partición de recuperación. En la mayoría de casos el equipo sigue funcionando con normalidad.",
    causes: [
      "Una instalación anterior de .NET Framework está dañada.",
      "La partición de recuperación no tiene espacio suficiente (actualización KB5034441).",
      "La actualización de Defender falló a mitad.",
    ],
    steps: [
      {
        tipo: "configuracion",
        title: "Mira qué actualización falla",
        detail: "En el historial verás el nombre exacto. Te dirá qué paso seguir.",
        how_to: "Configuración → Windows Update → Historial de actualizaciones.",
      },
      {
        tipo: "configuracion",
        title: "Si es de Microsoft Defender",
        detail: "Actualízalo desde la propia aplicación de seguridad en lugar de Windows Update.",
        how_to: "Abre «Seguridad de Windows» → Protección antivirus y contra amenazas → Actualizaciones de protección → Buscar actualizaciones.",
      },
      {
        tipo: "advertencia",
        title: "Si es KB5034441, no te preocupes",
        detail: "Esta actualización falla cuando la partición de recuperación es pequeña. Tu equipo funciona igual y está protegido. Corregirlo a mano implica modificar particiones, así que no lo hagas si no sabes exactamente lo que haces.",
      },
      {
        tipo: "configuracion",
        title: "Si es de .NET Framework",
        detail: "Ejecuta el solucionador de Windows Update y reinicia antes de volver a intentarlo.",
        how_to: "Configuración → Sistema → Solucionar problemas → Otros solucionadores de problemas → Windows Update.",
      },
      {
        tipo: "reinicio",
        title: "Reinicia e inténtalo otra vez",
        detail: "Muchas veces la actualización se instala sola en el segundo intento tras reiniciar.",
      },
    ],
    help: "Si falla una actualización de seguridad mensual (no Defender ni KB5034441), sigue también la guía del error 0x80070002.",
  },
  {
    id: "bsod-critical-process-died",
    code: "CRITICAL_PROCESS_DIED",
    aliases: ["0x000000EF", "0xEF"],
    category: "pantallazo",
    level: "media",
    time: "20–40 min",
    title: "Pantallazo azul: proceso crítico detenido",
    summary: "Una parte esencial de Windows se cerró de golpe y el equipo se reinició.",
    explanation:
      "Windows necesita ciertos programas internos para funcionar. Si uno de ellos se cierra inesperadamente, Windows se detiene para proteger tus datos. Lo más habitual es un archivo del sistema dañado o un controlador (driver) defectuoso.",
    causes: [
      "Archivos de Windows dañados.",
      "Un controlador instalado o actualizado hace poco.",
      "Problemas en el disco duro o SSD.",
    ],
    steps: [
      {
        tipo: "advertencia",
        title: "Guarda tus archivos importantes",
        detail: "Antes de nada, copia tus documentos a un USB o a la nube por si el problema empeora.",
      },
      {
        tipo: "configuracion",
        title: "Deshaz el último cambio",
        detail: "Si empezó tras instalar un programa, un driver o una actualización, desinstálalo.",
        how_to: "Configuración → Aplicaciones → Aplicaciones instaladas. Para actualizaciones: Windows Update → Historial → Desinstalar actualizaciones.",
      },
      {
        tipo: "terminal",
        title: "Repara los archivos de Windows",
        detail: "Comprueba y repara los archivos del sistema. Tarda entre 10 y 20 minutos.",
        how_to: "Abre la Terminal como administrador y ejecuta los comandos en este orden.",
        comando: "DISM /Online /Cleanup-Image /RestoreHealth\nsfc /scannow",
        command_explanation: "Si sfc dice que reparó archivos, reinicia y comprueba si el pantallazo vuelve a aparecer.",
      },
      {
        tipo: "terminal",
        title: "Revisa el disco",
        detail: "Busca errores en el disco y los corrige al reiniciar.",
        how_to: "En la Terminal de administrador ejecuta el comando y, cuando pregunte, pulsa S y Enter.",
        comando: "chkdsk C: /f",
        command_explanation: "La revisión se hace en el siguiente arranque y puede tardar un rato. No apagues el equipo.",
      },
      {
        tipo: "reinicio",
        title: "Vuelve a un punto anterior",
        detail: "Si nada funciona, Restaurar sistema devuelve Windows a como estaba antes del problema, sin tocar tus documentos.",
        how_to: "Pulsa Windows + R, escribe rstrui y pulsa Enter. Elige un punto de restauración anterior a cuando empezó el fallo.",
      },
    ],
    help: "Si Windows no llega a arrancar, después de dos reinicios fallidos aparece «Reparación automática». Desde ahí: Solucionar problemas → Opciones avanzadas → Restaurar sistema.",
  },
  {
    id: "bsod-irql",
    code: "IRQL_NOT_LESS_OR_EQUAL",
    aliases: ["0x0000000A", "0xA"],
    category: "pantallazo",
    level: "media",
    time: "20–40 min",
    title: "Pantallazo azul: IRQL_NOT_LESS_OR_EQUAL",
    summary: "Un controlador intentó usar memoria a la que no tenía acceso.",
    explanation:
      "Un controlador (el programa que hace funcionar una pieza como la tarjeta de red o la gráfica) accedió a una zona de memoria que no le correspondía. Casi siempre es un driver desactualizado o incompatible; con menos frecuencia, la memoria RAM.",
    causes: [
      "Un controlador desactualizado (a menudo red, Wi-Fi o antivirus).",
      "Un programa o driver instalado recientemente.",
      "Fallo de la memoria RAM.",
    ],
    steps: [
      {
        tipo: "configuracion",
        title: "Instala todas las actualizaciones",
        detail: "Incluye las opcionales, que suelen traer controladores nuevos.",
        how_to: "Configuración → Windows Update → Opciones avanzadas → Actualizaciones opcionales → Actualizaciones de controladores.",
      },
      {
        tipo: "configuracion",
        title: "Actualiza los controladores desde el fabricante",
        detail: "Entra en la web del fabricante de tu portátil o placa base (HP, Lenovo, ASUS, Dell…) y descarga los drivers de red, gráfica y chipset para tu modelo.",
        how_to: "El modelo exacto aparece en una pegatina debajo del portátil o en Configuración → Sistema → Información.",
      },
      {
        tipo: "configuracion",
        title: "Desinstala lo último que instalaste",
        detail: "Si el error empezó tras instalar un antivirus, una VPN o un programa de periféricos, desinstálalo y comprueba si se repite.",
        how_to: "Configuración → Aplicaciones → Aplicaciones instaladas → los tres puntos → Desinstalar.",
      },
      {
        tipo: "terminal",
        title: "Comprueba la memoria RAM",
        detail: "Windows tiene una herramienta que revisa la memoria. El equipo se reinicia y la prueba dura unos 15 minutos.",
        how_to: "Guarda todo, abre la Terminal y ejecuta el comando. Elige «Reiniciar ahora y comprobar si existen problemas».",
        comando: "mdsched.exe",
        command_explanation: "Al volver a Windows verás una notificación con el resultado. Si encuentra errores, la RAM debe revisarse o cambiarse.",
      },
    ],
    help: "Si el pantallazo aparece incluso en Modo seguro, es probable que sea hardware (RAM o disco): conviene llevarlo a un servicio técnico.",
  },
  {
    id: "bsod-memory-management",
    code: "MEMORY_MANAGEMENT",
    aliases: ["0x0000001A", "0x1A"],
    category: "pantallazo",
    level: "media",
    time: "20–40 min",
    title: "Pantallazo azul: problema de memoria",
    summary: "Windows detectó un fallo grave al gestionar la memoria RAM.",
    explanation:
      "Windows controla constantemente cómo se usa la memoria. Si encuentra datos que no tienen sentido, se detiene. Puede deberse a la propia RAM, a un controlador defectuoso o a archivos del sistema dañados.",
    causes: [
      "Un módulo de memoria RAM defectuoso o mal colocado.",
      "Configuración de memoria acelerada (XMP/EXPO) inestable.",
      "Controladores o archivos del sistema dañados.",
    ],
    steps: [
      {
        tipo: "terminal",
        title: "Haz la prueba de memoria",
        detail: "Es la comprobación más importante para este error.",
        how_to: "Guarda tu trabajo, abre la Terminal y ejecuta el comando. Elige «Reiniciar ahora».",
        comando: "mdsched.exe",
        command_explanation: "El resultado aparece como notificación al volver a entrar en Windows.",
      },
      {
        tipo: "advertencia",
        title: "¿Activaste XMP o EXPO en la BIOS?",
        detail: "Si aceleraste la memoria hace poco, desactiva ese perfil en la BIOS y comprueba si el error desaparece. Si no sabes qué es, sáltate este paso.",
      },
      {
        tipo: "terminal",
        title: "Repara los archivos de Windows",
        detail: "Descarta que el problema sea software.",
        how_to: "Abre la Terminal como administrador y ejecuta los comandos en orden.",
        comando: "DISM /Online /Cleanup-Image /RestoreHealth\nsfc /scannow",
        command_explanation: "Reinicia cuando terminen los dos.",
      },
      {
        tipo: "configuracion",
        title: "Actualiza los controladores",
        detail: "Especialmente el de la tarjeta gráfica y el chipset, desde la web del fabricante.",
        how_to: "Configuración → Windows Update → Opciones avanzadas → Actualizaciones opcionales.",
      },
    ],
    help: "Si la prueba de memoria encuentra errores, el problema es físico. En un sobremesa se puede probar cada módulo por separado; en un portátil, mejor un servicio técnico.",
  },
  {
    id: "bsod-video-tdr",
    code: "VIDEO_TDR_FAILURE",
    aliases: ["0x00000116", "0x116", "nvlddmkm.sys", "atikmpag.sys", "amdkmdag.sys", "igdkmd64.sys"],
    category: "pantallazo",
    level: "media",
    time: "15–30 min",
    title: "Pantallazo azul: fallo de la tarjeta gráfica",
    summary: "La tarjeta gráfica dejó de responder y Windows no pudo recuperarla.",
    explanation:
      "Cuando la gráfica se queda bloqueada, Windows intenta reiniciarla en segundo plano. Si no lo consigue, muestra este pantallazo. El nombre del archivo indica la marca: nvlddmkm.sys es NVIDIA, atikmpag.sys o amdkmdag.sys es AMD e igdkmd64.sys es Intel.",
    causes: [
      "El controlador de la gráfica está desactualizado o dañado.",
      "La gráfica se calienta demasiado (polvo o ventiladores sucios).",
      "Overclock de la gráfica inestable.",
    ],
    steps: [
      {
        tipo: "configuracion",
        title: "Instala el controlador oficial más reciente",
        detail: "Descárgalo solo de la web del fabricante: NVIDIA, AMD o Intel. En portátiles, mejor desde la web de la marca del portátil.",
        how_to: "Durante la instalación elige «Instalación limpia» si aparece esa opción.",
      },
      {
        tipo: "advertencia",
        title: "Quita cualquier overclock",
        detail: "Si usas MSI Afterburner u otro programa para acelerar la gráfica, vuelve a los valores de fábrica.",
      },
      {
        tipo: "configuracion",
        title: "Vigila la temperatura",
        detail: "Limpia el polvo de las rejillas y comprueba que los ventiladores giran. Un portátil debe estar sobre una superficie dura, no sobre una cama o un cojín.",
        how_to: "Administrador de tareas (Ctrl + Mayús + Esc) → Rendimiento → GPU muestra la temperatura en muchos equipos.",
      },
      {
        tipo: "reinicio",
        title: "Reinicia y prueba con calma",
        detail: "Usa el equipo con normalidad un par de días. Si el error vuelve con juegos o vídeo, la gráfica puede estar fallando.",
      },
    ],
    help: "Si el fallo continúa con el controlador limpio y la temperatura bien, la tarjeta gráfica puede estar averiada: consulta la garantía.",
  },
  {
    id: "bsod-inaccessible-boot",
    code: "INACCESSIBLE_BOOT_DEVICE",
    aliases: ["0x0000007B", "0x7B"],
    category: "pantallazo",
    level: "avanzada",
    time: "20–60 min",
    title: "Pantallazo azul: no se puede acceder al disco de arranque",
    summary: "Windows no encuentra o no puede leer el disco donde está instalado.",
    explanation:
      "Al arrancar, Windows no consigue leer el disco del sistema. Suele ocurrir tras cambiar algo en la BIOS, conectar discos nuevos, o después de una actualización que falló.",
    causes: [
      "Se cambió el modo del disco (AHCI/RAID) en la BIOS.",
      "Un disco o USB conectado confunde el arranque.",
      "Una actualización interrumpida o un disco con fallos.",
    ],
    steps: [
      {
        tipo: "configuracion",
        title: "Desconecta todo lo externo",
        detail: "Quita memorias USB, discos externos y tarjetas SD, y vuelve a encender.",
      },
      {
        tipo: "advertencia",
        title: "Ten a mano la clave de BitLocker",
        detail: "Al usar las herramientas de reparación, Windows puede pedirte una clave de recuperación. La encuentras en aka.ms/myrecoverykey desde otro dispositivo, con tu cuenta Microsoft.",
      },
      {
        tipo: "configuracion",
        title: "Deshaz cambios en la BIOS",
        detail: "Si tocaste la BIOS hace poco, vuelve a dejar el modo de almacenamiento como estaba (normalmente AHCI) o carga los valores por defecto.",
        how_to: "Entra en la BIOS al encender (suele ser F2, Supr o F10) y busca «Load Defaults» o «SATA Mode».",
      },
      {
        tipo: "reinicio",
        title: "Usa Reparación de inicio",
        detail: "Windows tiene una herramienta que repara el arranque automáticamente.",
        how_to: "Tras dos arranques fallidos aparece «Reparación automática» → Opciones avanzadas → Solucionar problemas → Opciones avanzadas → Reparación de inicio.",
      },
      {
        tipo: "reinicio",
        title: "Desinstala la última actualización",
        detail: "Si empezó después de actualizar, desde el mismo menú puedes quitarla.",
        how_to: "Solucionar problemas → Opciones avanzadas → Desinstalar actualizaciones → Desinstalar la actualización de calidad más reciente.",
      },
    ],
    help: "Si nada de esto funciona, el disco podría estar fallando. Antes de reinstalar Windows, intenta recuperar tus archivos con ayuda de un técnico.",
  },
  {
    id: "sys-0x80070005",
    code: "0x80070005",
    aliases: [],
    category: "sistema",
    level: "facil",
    time: "5–15 min",
    title: "Acceso denegado",
    summary: "No tienes permiso para modificar un archivo, una carpeta o un ajuste.",
    explanation:
      "Windows protege ciertos archivos y carpetas. Este error aparece cuando un programa, una actualización o tú mismo intentáis cambiar algo sin el permiso necesario. A veces el bloqueo lo provoca el antivirus.",
    causes: [
      "El programa no se está ejecutando como administrador.",
      "La protección «Acceso controlado a carpetas» bloquea el cambio.",
      "Los permisos de la carpeta están mal configurados.",
    ],
    steps: [
      {
        tipo: "configuracion",
        title: "Ejecuta el programa como administrador",
        detail: "Muchas veces basta con darle permisos de administrador.",
        how_to: "Clic derecho sobre el programa → «Ejecutar como administrador» → Sí.",
      },
      {
        tipo: "configuracion",
        title: "Revisa la protección contra ransomware",
        detail: "Esta protección impide que programas desconocidos escriban en Documentos, Imágenes, etc. Puedes permitir un programa concreto.",
        how_to: "Seguridad de Windows → Protección antivirus y contra amenazas → Administrar la protección contra ransomware → Permitir una aplicación.",
      },
      {
        tipo: "advertencia",
        title: "Pausa un momento tu antivirus de terceros",
        detail: "Si usas Avast, Norton, McAfee u otro, desactívalo unos minutos para probar. Vuelve a activarlo enseguida.",
      },
      {
        tipo: "terminal",
        title: "Si sale en Windows Update",
        detail: "Repara los archivos del sistema y vuelve a intentarlo.",
        how_to: "Abre la Terminal como administrador y ejecuta los comandos en orden.",
        comando: "DISM /Online /Cleanup-Image /RestoreHealth\nsfc /scannow",
        command_explanation: "Reinicia cuando terminen y vuelve a buscar actualizaciones.",
      },
    ],
    help: "Si tu cuenta no es de administrador (por ejemplo, un equipo del trabajo), tendrás que pedir a quien lo gestiona que haga el cambio.",
  },
  {
    id: "sys-0x80070570",
    code: "0x80070570",
    aliases: [],
    category: "sistema",
    level: "facil",
    time: "10–30 min",
    title: "El archivo está dañado o no se puede leer",
    summary: "Windows no puede leer un archivo porque está corrupto o incompleto.",
    explanation:
      "Ocurre al copiar archivos, descomprimir un ZIP o instalar Windows o un programa. El archivo llegó dañado o el lugar donde está guardado tiene errores.",
    causes: [
      "La descarga se cortó y el archivo está incompleto.",
      "El USB, el disco o el cable tienen fallos.",
      "Hay errores en el sistema de archivos del disco.",
    ],
    steps: [
      {
        tipo: "configuracion",
        title: "Vuelve a descargar el archivo",
        detail: "Bórralo y descárgalo otra vez, mejor por cable o con buena cobertura Wi-Fi.",
      },
      {
        tipo: "configuracion",
        title: "Prueba otro puerto USB o cable",
        detail: "Si copias desde un USB o disco externo, cámbialo de puerto (mejor uno trasero en sobremesa) o usa otro cable.",
      },
      {
        tipo: "terminal",
        title: "Revisa el disco",
        detail: "Comprueba y repara errores del disco. Cambia la letra si el problema está en otra unidad (por ejemplo D: o E:).",
        how_to: "Abre la Terminal como administrador. Si es el disco C:, pulsa S cuando pregunte y reinicia.",
        comando: "chkdsk C: /f",
        command_explanation: "No apagues el equipo mientras se revisa el disco.",
      },
      {
        tipo: "terminal",
        title: "Si pasa al instalar Windows, revisa la RAM",
        detail: "Una memoria RAM defectuosa también puede dañar archivos mientras se copian.",
        how_to: "Abre la Terminal y ejecuta el comando. Elige «Reiniciar ahora».",
        comando: "mdsched.exe",
        command_explanation: "El resultado aparece como notificación al volver a Windows.",
      },
    ],
    help: "Si el error aparece con muchos archivos distintos del mismo disco, haz copia de seguridad cuanto antes: el disco podría estar fallando.",
  },
  {
    id: "app-0xc000007b",
    code: "0xc000007b",
    aliases: [],
    category: "programas",
    level: "facil",
    time: "10–20 min",
    title: "La aplicación no se pudo iniciar correctamente",
    summary: "A un programa o juego le faltan componentes de Windows o están dañados.",
    explanation:
      "Muchos programas y juegos necesitan paquetes de Microsoft como Visual C++ o DirectX. Si faltan, están dañados o se mezclan versiones de 32 y 64 bits, el programa no arranca y muestra este error.",
    causes: [
      "Faltan los paquetes Visual C++ Redistributable.",
      "La instalación del programa está incompleta.",
      "Se mezclaron archivos de 32 y 64 bits.",
    ],
    steps: [
      {
        tipo: "reinicio",
        title: "Reinicia el equipo",
        detail: "Parece obvio, pero a veces una actualización pendiente es la causa.",
      },
      {
        tipo: "terminal",
        title: "Instala los paquetes Visual C++",
        detail: "Instala las dos versiones (64 y 32 bits): muchos programas de 64 bits también usan la de 32.",
        how_to: "Abre la Terminal como administrador y ejecuta las dos líneas.",
        comando: "winget install Microsoft.VCRedist.2015+.x64\nwinget install Microsoft.VCRedist.2015+.x86",
        command_explanation: "winget descarga los instaladores oficiales de Microsoft. Si te pregunta por los términos, escribe Y.",
      },
      {
        tipo: "configuracion",
        title: "Reinstala el programa",
        detail: "Desinstálalo y vuelve a instalarlo desde la web oficial. En Steam puedes usar «Verificar integridad de los archivos».",
        how_to: "Configuración → Aplicaciones → Aplicaciones instaladas → Desinstalar.",
      },
      {
        tipo: "advertencia",
        title: "No descargues DLL sueltas de Internet",
        detail: "Las webs que ofrecen DLL individuales pueden traer virus. Instala siempre los paquetes completos de Microsoft.",
      },
    ],
    help: "Si es un juego antiguo, instala también «DirectX End-User Runtime» desde la web de Microsoft.",
  },
  {
    id: "app-vcruntime",
    code: "VCRUNTIME140.dll",
    aliases: ["MSVCP140.dll", "VCRUNTIME140_1.dll"],
    category: "programas",
    level: "facil",
    time: "5 min",
    title: "Falta VCRUNTIME140.dll o MSVCP140.dll",
    summary: "El programa necesita un componente de Microsoft que no está instalado.",
    explanation:
      "Estos archivos forman parte del paquete Microsoft Visual C++ Redistributable. Muchos programas lo necesitan para funcionar. La solución es instalar el paquete oficial, no copiar el archivo suelto.",
    causes: [
      "El paquete Visual C++ no está instalado.",
      "El paquete se desinstaló o está dañado.",
      "El instalador del programa no lo incluyó.",
    ],
    steps: [
      {
        tipo: "terminal",
        title: "Instala Visual C++ Redistributable",
        detail: "Instala las versiones de 64 y 32 bits.",
        how_to: "Abre la Terminal como administrador y ejecuta las dos líneas.",
        comando: "winget install Microsoft.VCRedist.2015+.x64\nwinget install Microsoft.VCRedist.2015+.x86",
        command_explanation: "Instala los paquetes oficiales de Microsoft. Si ya estaban, winget te lo indicará.",
      },
      {
        tipo: "configuracion",
        title: "Si ya estaba instalado, repáralo",
        detail: "Busca «Microsoft Visual C++ 2015-2022 Redistributable» en la lista de aplicaciones y elige Modificar → Reparar.",
        how_to: "Configuración → Aplicaciones → Aplicaciones instaladas → los tres puntos → Modificar.",
      },
      {
        tipo: "advertencia",
        title: "No descargues la DLL suelta",
        detail: "Las webs de «descarga de DLL» son una vía habitual de virus. Usa siempre el paquete de Microsoft.",
      },
      {
        tipo: "reinicio",
        title: "Reinicia y abre el programa",
        detail: "Después de reiniciar, el programa debería encontrar el archivo.",
      },
    ],
    help: "Si sigue fallando, reinstala el programa que muestra el error: puede que su propia instalación esté incompleta.",
  },
  {
    id: "net-dns",
    code: "DNS_PROBE_FINISHED_NXDOMAIN",
    aliases: ["DNS_PROBE_FINISHED_NO_INTERNET", "ERR_NAME_NOT_RESOLVED"],
    category: "red",
    level: "facil",
    time: "5–15 min",
    title: "No se encuentra la dirección del sitio web",
    summary: "El navegador no consigue traducir el nombre de la web a una dirección.",
    explanation:
      "Para abrir una web, el equipo pregunta a un servidor DNS (una especie de agenda de Internet) su dirección. Si ese servidor no responde o tiene datos antiguos guardados, la página no carga aunque tengas conexión.",
    causes: [
      "El servidor DNS de tu proveedor no responde.",
      "Hay datos antiguos guardados en la caché DNS.",
      "Un fallo puntual del router.",
    ],
    steps: [
      {
        tipo: "configuracion",
        title: "Comprueba que la dirección está bien escrita",
        detail: "Y prueba a abrir otras webs. Si solo falla una, puede que esa web esté caída.",
      },
      {
        tipo: "reinicio",
        title: "Reinicia el router",
        detail: "Desenchúfalo 30 segundos y vuelve a enchufarlo. Espera a que las luces se estabilicen.",
      },
      {
        tipo: "terminal",
        title: "Limpia la caché DNS y la red",
        detail: "Borra las direcciones guardadas y restablece la configuración de red de Windows.",
        how_to: "Abre la Terminal como administrador, ejecuta las líneas y reinicia el equipo.",
        comando: "ipconfig /flushdns\nnetsh winsock reset\nnetsh int ip reset",
        command_explanation: "No borra tus redes Wi-Fi guardadas. Es necesario reiniciar para que se aplique.",
      },
      {
        tipo: "configuracion",
        title: "Usa un DNS público",
        detail: "Puedes usar los DNS gratuitos de Cloudflare (1.1.1.1) o Google (8.8.8.8).",
        how_to: "Configuración → Red e Internet → Wi-Fi o Ethernet → tu red → Asignación de servidor DNS → Editar → Manual → IPv4: 1.1.1.1 y 8.8.8.8.",
      },
    ],
    help: "Si ningún dispositivo de la casa puede navegar, el problema es del router o del proveedor: llama a su servicio técnico.",
  },
  {
    id: "act-0xc004f074",
    code: "0xC004F074",
    aliases: [],
    category: "sistema",
    level: "facil",
    time: "5–10 min",
    title: "Windows no se puede activar",
    summary: "No se pudo contactar con el servidor que valida la licencia.",
    explanation:
      "Windows comprueba que su licencia es válida conectándose a un servidor. En equipos de empresa o universidad ese servidor está en su red interna; en casa, es el de Microsoft. Si no se alcanza, aparece este error.",
    causes: [
      "El equipo pertenece a una organización y no está en su red.",
      "La fecha y la hora son incorrectas.",
      "Problemas temporales de conexión.",
    ],
    steps: [
      {
        tipo: "configuracion",
        title: "Comprueba la fecha y la hora",
        detail: "Una hora incorrecta impide la activación.",
        how_to: "Configuración → Hora e idioma → Fecha y hora → Sincronizar ahora.",
      },
      {
        tipo: "configuracion",
        title: "Si es un equipo de empresa o universidad",
        detail: "Conéctate a la red del centro o a su VPN y espera unos minutos: la activación se hace sola.",
      },
      {
        tipo: "terminal",
        title: "Fuerza la activación",
        detail: "Pide a Windows que vuelva a intentar activarse ahora mismo.",
        how_to: "Abre la Terminal como administrador y ejecuta el comando. Aparecerá una ventana con el resultado.",
        comando: "slmgr /ato",
        command_explanation: "Solo vuelve a intentar la activación; no cambia tu licencia.",
      },
      {
        tipo: "configuracion",
        title: "Usa el solucionador de activación",
        detail: "Útil si cambiaste piezas del equipo, como la placa base.",
        how_to: "Configuración → Sistema → Activación → Solucionar problemas.",
      },
    ],
    help: "Si el equipo es de tu empresa o centro de estudios, su departamento de informática es quien gestiona la licencia.",
  },
  {
    id: "perf-disk-100",
    code: "DISCO_100",
    aliases: ["DISCO AL 100", "DISCO AL 100%", "DISK 100%"],
    symptom: "Disco al 100 %",
    category: "sistema",
    level: "facil",
    time: "10–20 min",
    title: "El equipo va muy lento y el disco está al 100 %",
    summary: "Algo está usando el disco sin parar y todo se vuelve lento.",
    explanation:
      "Si el Administrador de tareas muestra el disco al 100 %, el equipo no puede leer ni guardar nada más deprisa. Pasa sobre todo en discos duros antiguos (HDD) y suele deberse a actualizaciones, análisis del antivirus o programas que arrancan al inicio.",
    causes: [
      "Windows Update o el antivirus están trabajando en segundo plano.",
      "Demasiados programas arrancan al encender el equipo.",
      "El disco duro es antiguo o empieza a fallar.",
    ],
    steps: [
      {
        tipo: "configuracion",
        title: "Mira qué está usando el disco",
        detail: "Ordena por la columna «Disco» para ver qué programa lo ocupa.",
        how_to: "Pulsa Ctrl + Mayús + Esc → pestaña Procesos → clic en la columna Disco.",
      },
      {
        tipo: "configuracion",
        title: "Espera si son actualizaciones",
        detail: "Si es Windows Update o el antivirus, déjalo terminar (10–30 minutos). Es normal justo después de encender.",
      },
      {
        tipo: "configuracion",
        title: "Quita programas del inicio",
        detail: "Desactiva los que no necesitas nada más encender: Spotify, Teams, launchers de juegos…",
        how_to: "Administrador de tareas → Aplicaciones de arranque → clic derecho → Deshabilitar.",
      },
      {
        tipo: "terminal",
        title: "Comprueba la salud del disco",
        detail: "Muestra si Windows considera que el disco está sano.",
        how_to: "Abre la Terminal (no hace falta administrador) y ejecuta el comando.",
        comando: "Get-PhysicalDisk | Select-Object FriendlyName, MediaType, HealthStatus",
        command_explanation: "Si HealthStatus no es «Healthy», haz copia de seguridad ya. MediaType «HDD» indica disco duro clásico.",
      },
    ],
    help: "Cambiar un disco duro clásico (HDD) por un SSD es la mejora que más acelera un equipo antiguo.",
  },
];
